"""Remove authentication system

Revision ID: b17cf3de0c39
Revises: b1ca66e327f4
Create Date: 2025-09-22 15:58:10.193962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b17cf3de0c39'
down_revision = 'b1ca66e327f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###